networks:
  pratilib.net:
    driver: bridge

services:
  # service api.pratilib : api pour la prise de rdv
  #
  api.pratilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./:/var/php
    working_dir: /var/php
    networks:
      - pratilib.net
    depends_on:
      - prati.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"


  prati.db:
    image: 'postgres:latest'
    env_file: ./pratidb.env.dist
    ports:
      - '5432:5432'
    networks:
      - pratilib.net
    volumes:
      - ./sql:/var/sql

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - pratilib.net